### PR TITLE
MiniDSP support: fixes #79

### LINKED ISSUE #79: Docker releases, automatic as part of release workflow
Would be great to get a docker image published as part of the release workflow.

- when a release tags are made, a github workflow will automatically publish a matching docker image to docker hub

There are a couple of docker image projects, but they're inactive / out of date:
https://github.com/jmery/ezbeq-docker
https://github.com/fattykidd/ezbeq-dc
https://hub.docker.com/search?q=ezbeq

### PR DESCRIPTION
**Pull request by astubbs**
Fixes https://github.com/3ll3d00d/ezbeq/issues/79

- Adds the latest release of the minidsp-rs rust application to the runtime environment.
- Also Improves the Dockerfile.

### CODE REVIEW

**Comment by astubbs** [comment]
Multi architecture flow incoming. I think it can be made to build in gh actions too...

**Comment by astubbs** [comment]
Linked to @jmery's [USB docker instructions](https://github.com/jmery/ezbeq-docker?tab=readme-ov-file#general-linux-docker-instructions), but maybe we should just copy them in? I can't test them/it though.

**Comment by astubbs** [comment]
I've pushed my locally built version of this here, if you want to test it: https://hub.docker.com/r/astubbs/ezbeq-jr

**Comment by astubbs** [comment]
Note, I added a place holder for a link from the ezbeq readme:

```mardown
> Why is this not mentioned in the ezBEQ readme?
 
It is, here: XXXXXX WIP!
```

**Comment by astubbs** [comment]
Proposed draft changes to ezBEQ readme:
https://github.com/3ll3d00d/ezbeq/compare/main...astubbs:docker-readme

**Comment by 3ll3d00d** [comment]
thanks for submitting!

**Comment by 3ll3d00d** [comment]
I also renamed the repo to ezbeq-docker

**Pull request merged**
